// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: container.proto

package labor_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	ModelName     string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{0}
}

func (x *StartServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *StartServiceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StartServiceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StartServiceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *StartServiceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type StartServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceResponse) Reset() {
	*x = StartServiceResponse{}
	mi := &file_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceResponse) ProtoMessage() {}

func (x *StartServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceResponse.ProtoReflect.Descriptor instead.
func (*StartServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{1}
}

func (x *StartServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Service Messages
type StopServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceRequest) Reset() {
	*x = StopServiceRequest{}
	mi := &file_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceRequest) ProtoMessage() {}

func (x *StopServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceRequest.ProtoReflect.Descriptor instead.
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2}
}

func (x *StopServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type StopServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceResponse) Reset() {
	*x = StopServiceResponse{}
	mi := &file_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceResponse) ProtoMessage() {}

func (x *StopServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceResponse.ProtoReflect.Descriptor instead.
func (*StopServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{3}
}

func (x *StopServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceRequest) Reset() {
	*x = RestartServiceRequest{}
	mi := &file_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceRequest) ProtoMessage() {}

func (x *RestartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceRequest.ProtoReflect.Descriptor instead.
func (*RestartServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4}
}

func (x *RestartServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type RestartServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartServiceResponse) Reset() {
	*x = RestartServiceResponse{}
	mi := &file_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartServiceResponse) ProtoMessage() {}

func (x *RestartServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartServiceResponse.ProtoReflect.Descriptor instead.
func (*RestartServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{5}
}

func (x *RestartServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServiceRequest) Reset() {
	*x = RemoveServiceRequest{}
	mi := &file_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServiceRequest) ProtoMessage() {}

func (x *RemoveServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServiceRequest.ProtoReflect.Descriptor instead.
func (*RemoveServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type RemoveServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveServiceResponse) Reset() {
	*x = RemoveServiceResponse{}
	mi := &file_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveServiceResponse) ProtoMessage() {}

func (x *RemoveServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveServiceResponse.ProtoReflect.Descriptor instead.
func (*RemoveServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BackupServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupServiceRequest) Reset() {
	*x = BackupServiceRequest{}
	mi := &file_container_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupServiceRequest) ProtoMessage() {}

func (x *BackupServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupServiceRequest.ProtoReflect.Descriptor instead.
func (*BackupServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{8}
}

func (x *BackupServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type BackupServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupUrl     string                 `protobuf:"bytes,1,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupServiceResponse) Reset() {
	*x = BackupServiceResponse{}
	mi := &file_container_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupServiceResponse) ProtoMessage() {}

func (x *BackupServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupServiceResponse.ProtoReflect.Descriptor instead.
func (*BackupServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{9}
}

func (x *BackupServiceResponse) GetBackupUrl() string {
	if x != nil {
		return x.BackupUrl
	}
	return ""
}

// Session Messages
type CompressSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressSessionRequest) Reset() {
	*x = CompressSessionRequest{}
	mi := &file_container_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressSessionRequest) ProtoMessage() {}

func (x *CompressSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressSessionRequest.ProtoReflect.Descriptor instead.
func (*CompressSessionRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{10}
}

func (x *CompressSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CompressSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressSessionResponse) Reset() {
	*x = CompressSessionResponse{}
	mi := &file_container_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressSessionResponse) ProtoMessage() {}

func (x *CompressSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressSessionResponse.ProtoReflect.Descriptor instead.
func (*CompressSessionResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{11}
}

func (x *CompressSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_container_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_container_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Dialogue Messages
type SendMessageToSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	IsStream      bool                   `protobuf:"varint,3,opt,name=is_stream,json=isStream,proto3" json:"is_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToSessionRequest) Reset() {
	*x = SendMessageToSessionRequest{}
	mi := &file_container_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToSessionRequest) ProtoMessage() {}

func (x *SendMessageToSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToSessionRequest.ProtoReflect.Descriptor instead.
func (*SendMessageToSessionRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{14}
}

func (x *SendMessageToSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageToSessionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageToSessionRequest) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

type SendMessageToSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaContent  string                 `protobuf:"bytes,1,opt,name=delta_content,json=deltaContent,proto3" json:"delta_content,omitempty"` // 流式返回时的片段内容
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`               // 是否是最后一段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToSessionResponse) Reset() {
	*x = SendMessageToSessionResponse{}
	mi := &file_container_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToSessionResponse) ProtoMessage() {}

func (x *SendMessageToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToSessionResponse.ProtoReflect.Descriptor instead.
func (*SendMessageToSessionResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{15}
}

func (x *SendMessageToSessionResponse) GetDeltaContent() string {
	if x != nil {
		return x.DeltaContent
	}
	return ""
}

func (x *SendMessageToSessionResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// Task Messages
type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_container_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{16}
}

func (x *StopTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_container_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{17}
}

func (x *StopTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RestartTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTaskRequest) Reset() {
	*x = RestartTaskRequest{}
	mi := &file_container_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTaskRequest) ProtoMessage() {}

func (x *RestartTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTaskRequest.ProtoReflect.Descriptor instead.
func (*RestartTaskRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{18}
}

func (x *RestartTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RestartTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartTaskResponse) Reset() {
	*x = RestartTaskResponse{}
	mi := &file_container_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartTaskResponse) ProtoMessage() {}

func (x *RestartTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartTaskResponse.ProtoReflect.Descriptor instead.
func (*RestartTaskResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{19}
}

func (x *RestartTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTaskRequest) Reset() {
	*x = RemoveTaskRequest{}
	mi := &file_container_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskRequest) ProtoMessage() {}

func (x *RemoveTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskRequest.ProtoReflect.Descriptor instead.
func (*RemoveTaskRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RemoveTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTaskResponse) Reset() {
	*x = RemoveTaskResponse{}
	mi := &file_container_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTaskResponse) ProtoMessage() {}

func (x *RemoveTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTaskResponse.ProtoReflect.Descriptor instead.
func (*RemoveTaskResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{21}
}

func (x *RemoveTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Skill Messages
type CreateSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	SkillName     string                 `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillRequest) Reset() {
	*x = CreateSkillRequest{}
	mi := &file_container_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillRequest) ProtoMessage() {}

func (x *CreateSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateSkillRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSkillRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateSkillRequest) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *CreateSkillRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSkillResponse) Reset() {
	*x = CreateSkillResponse{}
	mi := &file_container_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSkillResponse) ProtoMessage() {}

func (x *CreateSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSkillResponse.ProtoReflect.Descriptor instead.
func (*CreateSkillResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{23}
}

func (x *CreateSkillResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type DisableSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableSkillRequest) Reset() {
	*x = DisableSkillRequest{}
	mi := &file_container_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableSkillRequest) ProtoMessage() {}

func (x *DisableSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableSkillRequest.ProtoReflect.Descriptor instead.
func (*DisableSkillRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{24}
}

func (x *DisableSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type DisableSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableSkillResponse) Reset() {
	*x = DisableSkillResponse{}
	mi := &file_container_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableSkillResponse) ProtoMessage() {}

func (x *DisableSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableSkillResponse.ProtoReflect.Descriptor instead.
func (*DisableSkillResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{25}
}

func (x *DisableSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkillId       string                 `protobuf:"bytes,1,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSkillRequest) Reset() {
	*x = RemoveSkillRequest{}
	mi := &file_container_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillRequest) ProtoMessage() {}

func (x *RemoveSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillRequest.ProtoReflect.Descriptor instead.
func (*RemoveSkillRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveSkillRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type RemoveSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSkillResponse) Reset() {
	*x = RemoveSkillResponse{}
	mi := &file_container_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSkillResponse) ProtoMessage() {}

func (x *RemoveSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSkillResponse.ProtoReflect.Descriptor instead.
func (*RemoveSkillResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{27}
}

func (x *RemoveSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Tool Messages
type CreateToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToolRequest) Reset() {
	*x = CreateToolRequest{}
	mi := &file_container_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolRequest) ProtoMessage() {}

func (x *CreateToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolRequest.ProtoReflect.Descriptor instead.
func (*CreateToolRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{28}
}

func (x *CreateToolRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateToolRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *CreateToolRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToolResponse) Reset() {
	*x = CreateToolResponse{}
	mi := &file_container_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToolResponse) ProtoMessage() {}

func (x *CreateToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToolResponse.ProtoReflect.Descriptor instead.
func (*CreateToolResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{29}
}

func (x *CreateToolResponse) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type DisableToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableToolRequest) Reset() {
	*x = DisableToolRequest{}
	mi := &file_container_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableToolRequest) ProtoMessage() {}

func (x *DisableToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableToolRequest.ProtoReflect.Descriptor instead.
func (*DisableToolRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{30}
}

func (x *DisableToolRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type DisableToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableToolResponse) Reset() {
	*x = DisableToolResponse{}
	mi := &file_container_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableToolResponse) ProtoMessage() {}

func (x *DisableToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableToolResponse.ProtoReflect.Descriptor instead.
func (*DisableToolResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{31}
}

func (x *DisableToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolId        string                 `protobuf:"bytes,1,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveToolRequest) Reset() {
	*x = RemoveToolRequest{}
	mi := &file_container_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveToolRequest) ProtoMessage() {}

func (x *RemoveToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveToolRequest.ProtoReflect.Descriptor instead.
func (*RemoveToolRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{32}
}

func (x *RemoveToolRequest) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type RemoveToolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveToolResponse) Reset() {
	*x = RemoveToolResponse{}
	mi := &file_container_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveToolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveToolResponse) ProtoMessage() {}

func (x *RemoveToolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveToolResponse.ProtoReflect.Descriptor instead.
func (*RemoveToolResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{33}
}

func (x *RemoveToolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MCP Messages
type CreateMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	McpName       string                 `protobuf:"bytes,2,opt,name=mcp_name,json=mcpName,proto3" json:"mcp_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMCPRequest) Reset() {
	*x = CreateMCPRequest{}
	mi := &file_container_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMCPRequest) ProtoMessage() {}

func (x *CreateMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMCPRequest.ProtoReflect.Descriptor instead.
func (*CreateMCPRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{34}
}

func (x *CreateMCPRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateMCPRequest) GetMcpName() string {
	if x != nil {
		return x.McpName
	}
	return ""
}

func (x *CreateMCPRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpId         string                 `protobuf:"bytes,1,opt,name=mcp_id,json=mcpId,proto3" json:"mcp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMCPResponse) Reset() {
	*x = CreateMCPResponse{}
	mi := &file_container_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMCPResponse) ProtoMessage() {}

func (x *CreateMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMCPResponse.ProtoReflect.Descriptor instead.
func (*CreateMCPResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{35}
}

func (x *CreateMCPResponse) GetMcpId() string {
	if x != nil {
		return x.McpId
	}
	return ""
}

type DisableMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpId         string                 `protobuf:"bytes,1,opt,name=mcp_id,json=mcpId,proto3" json:"mcp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMCPRequest) Reset() {
	*x = DisableMCPRequest{}
	mi := &file_container_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMCPRequest) ProtoMessage() {}

func (x *DisableMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMCPRequest.ProtoReflect.Descriptor instead.
func (*DisableMCPRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{36}
}

func (x *DisableMCPRequest) GetMcpId() string {
	if x != nil {
		return x.McpId
	}
	return ""
}

type DisableMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableMCPResponse) Reset() {
	*x = DisableMCPResponse{}
	mi := &file_container_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableMCPResponse) ProtoMessage() {}

func (x *DisableMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableMCPResponse.ProtoReflect.Descriptor instead.
func (*DisableMCPResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{37}
}

func (x *DisableMCPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveMCPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpId         string                 `protobuf:"bytes,1,opt,name=mcp_id,json=mcpId,proto3" json:"mcp_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMCPRequest) Reset() {
	*x = RemoveMCPRequest{}
	mi := &file_container_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMCPRequest) ProtoMessage() {}

func (x *RemoveMCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMCPRequest.ProtoReflect.Descriptor instead.
func (*RemoveMCPRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{38}
}

func (x *RemoveMCPRequest) GetMcpId() string {
	if x != nil {
		return x.McpId
	}
	return ""
}

type RemoveMCPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMCPResponse) Reset() {
	*x = RemoveMCPResponse{}
	mi := &file_container_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMCPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMCPResponse) ProtoMessage() {}

func (x *RemoveMCPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMCPResponse.ProtoReflect.Descriptor instead.
func (*RemoveMCPResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{39}
}

func (x *RemoveMCPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_container_proto protoreflect.FileDescriptor

const file_container_proto_rawDesc = "" +
	"\n" +
	"\x0fcontainer.proto\x12\x05labor\"\x93\x01\n" +
	"\x13StartServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\"0\n" +
	"\x14StartServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x12StopServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"/\n" +
	"\x13StopServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x15RestartServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"2\n" +
	"\x16RestartServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14RemoveServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"1\n" +
	"\x15RemoveServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x14BackupServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"6\n" +
	"\x15BackupServiceResponse\x12\x1d\n" +
	"\n" +
	"backup_url\x18\x01 \x01(\tR\tbackupUrl\"7\n" +
	"\x16CompressSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"8\n" +
	"\x17CompressSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\x14RemoveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"1\n" +
	"\x15RemoveSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x1bSendMessageToSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tis_stream\x18\x03 \x01(\bR\bisStream\"^\n" +
	"\x1cSendMessageToSessionResponse\x12#\n" +
	"\rdelta_content\x18\x01 \x01(\tR\fdeltaContent\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\"0\n" +
	"\x0fStopTaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\",\n" +
	"\x10StopTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x12RestartTaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"/\n" +
	"\x13RestartTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x11RemoveTaskRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\".\n" +
	"\x12RemoveTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd8\x01\n" +
	"\x12CreateSkillRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x02 \x01(\tR\tskillName\x12C\n" +
	"\bmetadata\x18\x03 \x03(\v2'.labor.CreateSkillRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x13CreateSkillResponse\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\"0\n" +
	"\x13DisableSkillRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\"0\n" +
	"\x14DisableSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\x12RemoveSkillRequest\x12\x19\n" +
	"\bskill_id\x18\x01 \x01(\tR\askillId\"/\n" +
	"\x13RemoveSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd4\x01\n" +
	"\x11CreateToolRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12B\n" +
	"\bmetadata\x18\x03 \x03(\v2&.labor.CreateToolRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x12CreateToolResponse\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"-\n" +
	"\x12DisableToolRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\"/\n" +
	"\x13DisableToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x11RemoveToolRequest\x12\x17\n" +
	"\atool_id\x18\x01 \x01(\tR\x06toolId\".\n" +
	"\x12RemoveToolResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xd0\x01\n" +
	"\x10CreateMCPRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bmcp_name\x18\x02 \x01(\tR\amcpName\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.labor.CreateMCPRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"*\n" +
	"\x11CreateMCPResponse\x12\x15\n" +
	"\x06mcp_id\x18\x01 \x01(\tR\x05mcpId\"*\n" +
	"\x11DisableMCPRequest\x12\x15\n" +
	"\x06mcp_id\x18\x01 \x01(\tR\x05mcpId\".\n" +
	"\x12DisableMCPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x10RemoveMCPRequest\x12\x15\n" +
	"\x06mcp_id\x18\x01 \x01(\tR\x05mcpId\"-\n" +
	"\x11RemoveMCPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb3\v\n" +
	"\x10ContainerService\x12G\n" +
	"\fStartService\x12\x1a.labor.StartServiceRequest\x1a\x1b.labor.StartServiceResponse\x12D\n" +
	"\vStopService\x12\x19.labor.StopServiceRequest\x1a\x1a.labor.StopServiceResponse\x12M\n" +
	"\x0eRestartService\x12\x1c.labor.RestartServiceRequest\x1a\x1d.labor.RestartServiceResponse\x12J\n" +
	"\rRemoveService\x12\x1b.labor.RemoveServiceRequest\x1a\x1c.labor.RemoveServiceResponse\x12J\n" +
	"\rBackupService\x12\x1b.labor.BackupServiceRequest\x1a\x1c.labor.BackupServiceResponse\x12J\n" +
	"\rRemoveSession\x12\x1b.labor.RemoveSessionRequest\x1a\x1c.labor.RemoveSessionResponse\x12P\n" +
	"\x0fCompressSession\x12\x1d.labor.CompressSessionRequest\x1a\x1e.labor.CompressSessionResponse\x12a\n" +
	"\x14SendMessageToSession\x12\".labor.SendMessageToSessionRequest\x1a#.labor.SendMessageToSessionResponse0\x01\x12;\n" +
	"\bStopTask\x12\x16.labor.StopTaskRequest\x1a\x17.labor.StopTaskResponse\x12D\n" +
	"\vRestartTask\x12\x19.labor.RestartTaskRequest\x1a\x1a.labor.RestartTaskResponse\x12A\n" +
	"\n" +
	"RemoveTask\x12\x18.labor.RemoveTaskRequest\x1a\x19.labor.RemoveTaskResponse\x12D\n" +
	"\vCreateSkill\x12\x19.labor.CreateSkillRequest\x1a\x1a.labor.CreateSkillResponse\x12G\n" +
	"\fDisableSkill\x12\x1a.labor.DisableSkillRequest\x1a\x1b.labor.DisableSkillResponse\x12D\n" +
	"\vRemoveSkill\x12\x19.labor.RemoveSkillRequest\x1a\x1a.labor.RemoveSkillResponse\x12A\n" +
	"\n" +
	"CreateTool\x12\x18.labor.CreateToolRequest\x1a\x19.labor.CreateToolResponse\x12D\n" +
	"\vDisableTool\x12\x19.labor.DisableToolRequest\x1a\x1a.labor.DisableToolResponse\x12A\n" +
	"\n" +
	"RemoveTool\x12\x18.labor.RemoveToolRequest\x1a\x19.labor.RemoveToolResponse\x12>\n" +
	"\tCreateMCP\x12\x17.labor.CreateMCPRequest\x1a\x18.labor.CreateMCPResponse\x12A\n" +
	"\n" +
	"DisableMCP\x12\x18.labor.DisableMCPRequest\x1a\x19.labor.DisableMCPResponse\x12>\n" +
	"\tRemoveMCP\x12\x17.labor.RemoveMCPRequest\x1a\x18.labor.RemoveMCPResponseB\n" +
	"Z\blabor.v1b\x06proto3"

var (
	file_container_proto_rawDescOnce sync.Once
	file_container_proto_rawDescData []byte
)

func file_container_proto_rawDescGZIP() []byte {
	file_container_proto_rawDescOnce.Do(func() {
		file_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)))
	})
	return file_container_proto_rawDescData
}

var file_container_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_container_proto_goTypes = []any{
	(*StartServiceRequest)(nil),          // 0: labor.StartServiceRequest
	(*StartServiceResponse)(nil),         // 1: labor.StartServiceResponse
	(*StopServiceRequest)(nil),           // 2: labor.StopServiceRequest
	(*StopServiceResponse)(nil),          // 3: labor.StopServiceResponse
	(*RestartServiceRequest)(nil),        // 4: labor.RestartServiceRequest
	(*RestartServiceResponse)(nil),       // 5: labor.RestartServiceResponse
	(*RemoveServiceRequest)(nil),         // 6: labor.RemoveServiceRequest
	(*RemoveServiceResponse)(nil),        // 7: labor.RemoveServiceResponse
	(*BackupServiceRequest)(nil),         // 8: labor.BackupServiceRequest
	(*BackupServiceResponse)(nil),        // 9: labor.BackupServiceResponse
	(*CompressSessionRequest)(nil),       // 10: labor.CompressSessionRequest
	(*CompressSessionResponse)(nil),      // 11: labor.CompressSessionResponse
	(*RemoveSessionRequest)(nil),         // 12: labor.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),        // 13: labor.RemoveSessionResponse
	(*SendMessageToSessionRequest)(nil),  // 14: labor.SendMessageToSessionRequest
	(*SendMessageToSessionResponse)(nil), // 15: labor.SendMessageToSessionResponse
	(*StopTaskRequest)(nil),              // 16: labor.StopTaskRequest
	(*StopTaskResponse)(nil),             // 17: labor.StopTaskResponse
	(*RestartTaskRequest)(nil),           // 18: labor.RestartTaskRequest
	(*RestartTaskResponse)(nil),          // 19: labor.RestartTaskResponse
	(*RemoveTaskRequest)(nil),            // 20: labor.RemoveTaskRequest
	(*RemoveTaskResponse)(nil),           // 21: labor.RemoveTaskResponse
	(*CreateSkillRequest)(nil),           // 22: labor.CreateSkillRequest
	(*CreateSkillResponse)(nil),          // 23: labor.CreateSkillResponse
	(*DisableSkillRequest)(nil),          // 24: labor.DisableSkillRequest
	(*DisableSkillResponse)(nil),         // 25: labor.DisableSkillResponse
	(*RemoveSkillRequest)(nil),           // 26: labor.RemoveSkillRequest
	(*RemoveSkillResponse)(nil),          // 27: labor.RemoveSkillResponse
	(*CreateToolRequest)(nil),            // 28: labor.CreateToolRequest
	(*CreateToolResponse)(nil),           // 29: labor.CreateToolResponse
	(*DisableToolRequest)(nil),           // 30: labor.DisableToolRequest
	(*DisableToolResponse)(nil),          // 31: labor.DisableToolResponse
	(*RemoveToolRequest)(nil),            // 32: labor.RemoveToolRequest
	(*RemoveToolResponse)(nil),           // 33: labor.RemoveToolResponse
	(*CreateMCPRequest)(nil),             // 34: labor.CreateMCPRequest
	(*CreateMCPResponse)(nil),            // 35: labor.CreateMCPResponse
	(*DisableMCPRequest)(nil),            // 36: labor.DisableMCPRequest
	(*DisableMCPResponse)(nil),           // 37: labor.DisableMCPResponse
	(*RemoveMCPRequest)(nil),             // 38: labor.RemoveMCPRequest
	(*RemoveMCPResponse)(nil),            // 39: labor.RemoveMCPResponse
	nil,                                  // 40: labor.CreateSkillRequest.MetadataEntry
	nil,                                  // 41: labor.CreateToolRequest.MetadataEntry
	nil,                                  // 42: labor.CreateMCPRequest.MetadataEntry
}
var file_container_proto_depIdxs = []int32{
	40, // 0: labor.CreateSkillRequest.metadata:type_name -> labor.CreateSkillRequest.MetadataEntry
	41, // 1: labor.CreateToolRequest.metadata:type_name -> labor.CreateToolRequest.MetadataEntry
	42, // 2: labor.CreateMCPRequest.metadata:type_name -> labor.CreateMCPRequest.MetadataEntry
	0,  // 3: labor.ContainerService.StartService:input_type -> labor.StartServiceRequest
	2,  // 4: labor.ContainerService.StopService:input_type -> labor.StopServiceRequest
	4,  // 5: labor.ContainerService.RestartService:input_type -> labor.RestartServiceRequest
	6,  // 6: labor.ContainerService.RemoveService:input_type -> labor.RemoveServiceRequest
	8,  // 7: labor.ContainerService.BackupService:input_type -> labor.BackupServiceRequest
	12, // 8: labor.ContainerService.RemoveSession:input_type -> labor.RemoveSessionRequest
	10, // 9: labor.ContainerService.CompressSession:input_type -> labor.CompressSessionRequest
	14, // 10: labor.ContainerService.SendMessageToSession:input_type -> labor.SendMessageToSessionRequest
	16, // 11: labor.ContainerService.StopTask:input_type -> labor.StopTaskRequest
	18, // 12: labor.ContainerService.RestartTask:input_type -> labor.RestartTaskRequest
	20, // 13: labor.ContainerService.RemoveTask:input_type -> labor.RemoveTaskRequest
	22, // 14: labor.ContainerService.CreateSkill:input_type -> labor.CreateSkillRequest
	24, // 15: labor.ContainerService.DisableSkill:input_type -> labor.DisableSkillRequest
	26, // 16: labor.ContainerService.RemoveSkill:input_type -> labor.RemoveSkillRequest
	28, // 17: labor.ContainerService.CreateTool:input_type -> labor.CreateToolRequest
	30, // 18: labor.ContainerService.DisableTool:input_type -> labor.DisableToolRequest
	32, // 19: labor.ContainerService.RemoveTool:input_type -> labor.RemoveToolRequest
	34, // 20: labor.ContainerService.CreateMCP:input_type -> labor.CreateMCPRequest
	36, // 21: labor.ContainerService.DisableMCP:input_type -> labor.DisableMCPRequest
	38, // 22: labor.ContainerService.RemoveMCP:input_type -> labor.RemoveMCPRequest
	1,  // 23: labor.ContainerService.StartService:output_type -> labor.StartServiceResponse
	3,  // 24: labor.ContainerService.StopService:output_type -> labor.StopServiceResponse
	5,  // 25: labor.ContainerService.RestartService:output_type -> labor.RestartServiceResponse
	7,  // 26: labor.ContainerService.RemoveService:output_type -> labor.RemoveServiceResponse
	9,  // 27: labor.ContainerService.BackupService:output_type -> labor.BackupServiceResponse
	13, // 28: labor.ContainerService.RemoveSession:output_type -> labor.RemoveSessionResponse
	11, // 29: labor.ContainerService.CompressSession:output_type -> labor.CompressSessionResponse
	15, // 30: labor.ContainerService.SendMessageToSession:output_type -> labor.SendMessageToSessionResponse
	17, // 31: labor.ContainerService.StopTask:output_type -> labor.StopTaskResponse
	19, // 32: labor.ContainerService.RestartTask:output_type -> labor.RestartTaskResponse
	21, // 33: labor.ContainerService.RemoveTask:output_type -> labor.RemoveTaskResponse
	23, // 34: labor.ContainerService.CreateSkill:output_type -> labor.CreateSkillResponse
	25, // 35: labor.ContainerService.DisableSkill:output_type -> labor.DisableSkillResponse
	27, // 36: labor.ContainerService.RemoveSkill:output_type -> labor.RemoveSkillResponse
	29, // 37: labor.ContainerService.CreateTool:output_type -> labor.CreateToolResponse
	31, // 38: labor.ContainerService.DisableTool:output_type -> labor.DisableToolResponse
	33, // 39: labor.ContainerService.RemoveTool:output_type -> labor.RemoveToolResponse
	35, // 40: labor.ContainerService.CreateMCP:output_type -> labor.CreateMCPResponse
	37, // 41: labor.ContainerService.DisableMCP:output_type -> labor.DisableMCPResponse
	39, // 42: labor.ContainerService.RemoveMCP:output_type -> labor.RemoveMCPResponse
	23, // [23:43] is the sub-list for method output_type
	3,  // [3:23] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_container_proto_init() }
func file_container_proto_init() {
	if File_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_proto_goTypes,
		DependencyIndexes: file_container_proto_depIdxs,
		MessageInfos:      file_container_proto_msgTypes,
	}.Build()
	File_container_proto = out.File
	file_container_proto_goTypes = nil
	file_container_proto_depIdxs = nil
}
