// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: container.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContainerService_BackupService_FullMethodName        = "/labor.v1.ContainerService/BackupService"
	ContainerService_StartFTPServer_FullMethodName       = "/labor.v1.ContainerService/StartFTPServer"
	ContainerService_StopFTPServer_FullMethodName        = "/labor.v1.ContainerService/StopFTPServer"
	ContainerService_StartVirtualDesktop_FullMethodName  = "/labor.v1.ContainerService/StartVirtualDesktop"
	ContainerService_StopVirtualDesktop_FullMethodName   = "/labor.v1.ContainerService/StopVirtualDesktop"
	ContainerService_CreateChatModel_FullMethodName      = "/labor.v1.ContainerService/CreateChatModel"
	ContainerService_RemoveChatModel_FullMethodName      = "/labor.v1.ContainerService/RemoveChatModel"
	ContainerService_CreateAgent_FullMethodName          = "/labor.v1.ContainerService/CreateAgent"
	ContainerService_RemoveAgent_FullMethodName          = "/labor.v1.ContainerService/RemoveAgent"
	ContainerService_GetAgentSession_FullMethodName      = "/labor.v1.ContainerService/GetAgentSession"
	ContainerService_ClearAgentHistory_FullMethodName    = "/labor.v1.ContainerService/ClearAgentHistory"
	ContainerService_CompressAgentHistory_FullMethodName = "/labor.v1.ContainerService/CompressAgentHistory"
	ContainerService_SendMessage_FullMethodName          = "/labor.v1.ContainerService/SendMessage"
	ContainerService_StopTask_FullMethodName             = "/labor.v1.ContainerService/StopTask"
)

// ContainerServiceClient is the client API for ContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 数字助理容器服务
// 一个 Agent 绑定一个 Session，agent_id 即 session_id
type ContainerServiceClient interface {
	// --- 容器 ---
	BackupService(ctx context.Context, in *BackupServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupServiceResponse], error)
	// --- FTP ---
	StartFTPServer(ctx context.Context, in *StartFTPServerRequest, opts ...grpc.CallOption) (*StartFTPServerResponse, error)
	StopFTPServer(ctx context.Context, in *StopFTPServerRequest, opts ...grpc.CallOption) (*StopFTPServerResponse, error)
	// --- 虚拟桌面 ---
	StartVirtualDesktop(ctx context.Context, in *StartVirtualDesktopRequest, opts ...grpc.CallOption) (*StartVirtualDesktopResponse, error)
	StopVirtualDesktop(ctx context.Context, in *StopVirtualDesktopRequest, opts ...grpc.CallOption) (*StopVirtualDesktopResponse, error)
	// --- 模型 ---
	CreateChatModel(ctx context.Context, in *CreateChatModelRequest, opts ...grpc.CallOption) (*CreateChatModelResponse, error)
	RemoveChatModel(ctx context.Context, in *RemoveChatModelRequest, opts ...grpc.CallOption) (*RemoveChatModelResponse, error)
	// --- 智能体 ---
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error)
	RemoveAgent(ctx context.Context, in *RemoveAgentRequest, opts ...grpc.CallOption) (*RemoveAgentResponse, error)
	// --- 会话 (agent 维度) ---
	GetAgentSession(ctx context.Context, in *GetAgentSessionRequest, opts ...grpc.CallOption) (*GetAgentSessionResponse, error)
	ClearAgentHistory(ctx context.Context, in *ClearAgentHistoryRequest, opts ...grpc.CallOption) (*ClearAgentHistoryResponse, error)
	CompressAgentHistory(ctx context.Context, in *CompressAgentHistoryRequest, opts ...grpc.CallOption) (*CompressAgentHistoryResponse, error)
	// --- 对话 ---
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendMessageResponse], error)
	// --- 任务 ---
	StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error)
}

type containerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerServiceClient(cc grpc.ClientConnInterface) ContainerServiceClient {
	return &containerServiceClient{cc}
}

func (c *containerServiceClient) BackupService(ctx context.Context, in *BackupServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BackupServiceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerService_ServiceDesc.Streams[0], ContainerService_BackupService_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BackupServiceRequest, BackupServiceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerService_BackupServiceClient = grpc.ServerStreamingClient[BackupServiceResponse]

func (c *containerServiceClient) StartFTPServer(ctx context.Context, in *StartFTPServerRequest, opts ...grpc.CallOption) (*StartFTPServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartFTPServerResponse)
	err := c.cc.Invoke(ctx, ContainerService_StartFTPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) StopFTPServer(ctx context.Context, in *StopFTPServerRequest, opts ...grpc.CallOption) (*StopFTPServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopFTPServerResponse)
	err := c.cc.Invoke(ctx, ContainerService_StopFTPServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) StartVirtualDesktop(ctx context.Context, in *StartVirtualDesktopRequest, opts ...grpc.CallOption) (*StartVirtualDesktopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVirtualDesktopResponse)
	err := c.cc.Invoke(ctx, ContainerService_StartVirtualDesktop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) StopVirtualDesktop(ctx context.Context, in *StopVirtualDesktopRequest, opts ...grpc.CallOption) (*StopVirtualDesktopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVirtualDesktopResponse)
	err := c.cc.Invoke(ctx, ContainerService_StopVirtualDesktop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) CreateChatModel(ctx context.Context, in *CreateChatModelRequest, opts ...grpc.CallOption) (*CreateChatModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateChatModelResponse)
	err := c.cc.Invoke(ctx, ContainerService_CreateChatModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) RemoveChatModel(ctx context.Context, in *RemoveChatModelRequest, opts ...grpc.CallOption) (*RemoveChatModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveChatModelResponse)
	err := c.cc.Invoke(ctx, ContainerService_RemoveChatModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*CreateAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAgentResponse)
	err := c.cc.Invoke(ctx, ContainerService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) RemoveAgent(ctx context.Context, in *RemoveAgentRequest, opts ...grpc.CallOption) (*RemoveAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAgentResponse)
	err := c.cc.Invoke(ctx, ContainerService_RemoveAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) GetAgentSession(ctx context.Context, in *GetAgentSessionRequest, opts ...grpc.CallOption) (*GetAgentSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentSessionResponse)
	err := c.cc.Invoke(ctx, ContainerService_GetAgentSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) ClearAgentHistory(ctx context.Context, in *ClearAgentHistoryRequest, opts ...grpc.CallOption) (*ClearAgentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearAgentHistoryResponse)
	err := c.cc.Invoke(ctx, ContainerService_ClearAgentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) CompressAgentHistory(ctx context.Context, in *CompressAgentHistoryRequest, opts ...grpc.CallOption) (*CompressAgentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompressAgentHistoryResponse)
	err := c.cc.Invoke(ctx, ContainerService_CompressAgentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SendMessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ContainerService_ServiceDesc.Streams[1], ContainerService_SendMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendMessageRequest, SendMessageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerService_SendMessageClient = grpc.ServerStreamingClient[SendMessageResponse]

func (c *containerServiceClient) StopTask(ctx context.Context, in *StopTaskRequest, opts ...grpc.CallOption) (*StopTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTaskResponse)
	err := c.cc.Invoke(ctx, ContainerService_StopTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerServiceServer is the server API for ContainerService service.
// All implementations must embed UnimplementedContainerServiceServer
// for forward compatibility.
//
// 数字助理容器服务
// 一个 Agent 绑定一个 Session，agent_id 即 session_id
type ContainerServiceServer interface {
	// --- 容器 ---
	BackupService(*BackupServiceRequest, grpc.ServerStreamingServer[BackupServiceResponse]) error
	// --- FTP ---
	StartFTPServer(context.Context, *StartFTPServerRequest) (*StartFTPServerResponse, error)
	StopFTPServer(context.Context, *StopFTPServerRequest) (*StopFTPServerResponse, error)
	// --- 虚拟桌面 ---
	StartVirtualDesktop(context.Context, *StartVirtualDesktopRequest) (*StartVirtualDesktopResponse, error)
	StopVirtualDesktop(context.Context, *StopVirtualDesktopRequest) (*StopVirtualDesktopResponse, error)
	// --- 模型 ---
	CreateChatModel(context.Context, *CreateChatModelRequest) (*CreateChatModelResponse, error)
	RemoveChatModel(context.Context, *RemoveChatModelRequest) (*RemoveChatModelResponse, error)
	// --- 智能体 ---
	CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error)
	RemoveAgent(context.Context, *RemoveAgentRequest) (*RemoveAgentResponse, error)
	// --- 会话 (agent 维度) ---
	GetAgentSession(context.Context, *GetAgentSessionRequest) (*GetAgentSessionResponse, error)
	ClearAgentHistory(context.Context, *ClearAgentHistoryRequest) (*ClearAgentHistoryResponse, error)
	CompressAgentHistory(context.Context, *CompressAgentHistoryRequest) (*CompressAgentHistoryResponse, error)
	// --- 对话 ---
	SendMessage(*SendMessageRequest, grpc.ServerStreamingServer[SendMessageResponse]) error
	// --- 任务 ---
	StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error)
	mustEmbedUnimplementedContainerServiceServer()
}

// UnimplementedContainerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContainerServiceServer struct{}

func (UnimplementedContainerServiceServer) BackupService(*BackupServiceRequest, grpc.ServerStreamingServer[BackupServiceResponse]) error {
	return status.Error(codes.Unimplemented, "method BackupService not implemented")
}
func (UnimplementedContainerServiceServer) StartFTPServer(context.Context, *StartFTPServerRequest) (*StartFTPServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartFTPServer not implemented")
}
func (UnimplementedContainerServiceServer) StopFTPServer(context.Context, *StopFTPServerRequest) (*StopFTPServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopFTPServer not implemented")
}
func (UnimplementedContainerServiceServer) StartVirtualDesktop(context.Context, *StartVirtualDesktopRequest) (*StartVirtualDesktopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVirtualDesktop not implemented")
}
func (UnimplementedContainerServiceServer) StopVirtualDesktop(context.Context, *StopVirtualDesktopRequest) (*StopVirtualDesktopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVirtualDesktop not implemented")
}
func (UnimplementedContainerServiceServer) CreateChatModel(context.Context, *CreateChatModelRequest) (*CreateChatModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChatModel not implemented")
}
func (UnimplementedContainerServiceServer) RemoveChatModel(context.Context, *RemoveChatModelRequest) (*RemoveChatModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveChatModel not implemented")
}
func (UnimplementedContainerServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*CreateAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedContainerServiceServer) RemoveAgent(context.Context, *RemoveAgentRequest) (*RemoveAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAgent not implemented")
}
func (UnimplementedContainerServiceServer) GetAgentSession(context.Context, *GetAgentSessionRequest) (*GetAgentSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgentSession not implemented")
}
func (UnimplementedContainerServiceServer) ClearAgentHistory(context.Context, *ClearAgentHistoryRequest) (*ClearAgentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearAgentHistory not implemented")
}
func (UnimplementedContainerServiceServer) CompressAgentHistory(context.Context, *CompressAgentHistoryRequest) (*CompressAgentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompressAgentHistory not implemented")
}
func (UnimplementedContainerServiceServer) SendMessage(*SendMessageRequest, grpc.ServerStreamingServer[SendMessageResponse]) error {
	return status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedContainerServiceServer) StopTask(context.Context, *StopTaskRequest) (*StopTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTask not implemented")
}
func (UnimplementedContainerServiceServer) mustEmbedUnimplementedContainerServiceServer() {}
func (UnimplementedContainerServiceServer) testEmbeddedByValue()                          {}

// UnsafeContainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerServiceServer will
// result in compilation errors.
type UnsafeContainerServiceServer interface {
	mustEmbedUnimplementedContainerServiceServer()
}

func RegisterContainerServiceServer(s grpc.ServiceRegistrar, srv ContainerServiceServer) {
	// If the following call panics, it indicates UnimplementedContainerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContainerService_ServiceDesc, srv)
}

func _ContainerService_BackupService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BackupServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContainerServiceServer).BackupService(m, &grpc.GenericServerStream[BackupServiceRequest, BackupServiceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerService_BackupServiceServer = grpc.ServerStreamingServer[BackupServiceResponse]

func _ContainerService_StartFTPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartFTPServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).StartFTPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_StartFTPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).StartFTPServer(ctx, req.(*StartFTPServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_StopFTPServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopFTPServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).StopFTPServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_StopFTPServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).StopFTPServer(ctx, req.(*StopFTPServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_StartVirtualDesktop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVirtualDesktopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).StartVirtualDesktop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_StartVirtualDesktop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).StartVirtualDesktop(ctx, req.(*StartVirtualDesktopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_StopVirtualDesktop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVirtualDesktopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).StopVirtualDesktop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_StopVirtualDesktop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).StopVirtualDesktop(ctx, req.(*StopVirtualDesktopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_CreateChatModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChatModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CreateChatModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_CreateChatModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CreateChatModel(ctx, req.(*CreateChatModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_RemoveChatModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveChatModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).RemoveChatModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_RemoveChatModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).RemoveChatModel(ctx, req.(*RemoveChatModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_RemoveAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).RemoveAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_RemoveAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).RemoveAgent(ctx, req.(*RemoveAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_GetAgentSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).GetAgentSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_GetAgentSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).GetAgentSession(ctx, req.(*GetAgentSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_ClearAgentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAgentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).ClearAgentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_ClearAgentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).ClearAgentHistory(ctx, req.(*ClearAgentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_CompressAgentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressAgentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CompressAgentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_CompressAgentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CompressAgentHistory(ctx, req.(*CompressAgentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_SendMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContainerServiceServer).SendMessage(m, &grpc.GenericServerStream[SendMessageRequest, SendMessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ContainerService_SendMessageServer = grpc.ServerStreamingServer[SendMessageResponse]

func _ContainerService_StopTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).StopTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContainerService_StopTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).StopTask(ctx, req.(*StopTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerService_ServiceDesc is the grpc.ServiceDesc for ContainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "labor.v1.ContainerService",
	HandlerType: (*ContainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartFTPServer",
			Handler:    _ContainerService_StartFTPServer_Handler,
		},
		{
			MethodName: "StopFTPServer",
			Handler:    _ContainerService_StopFTPServer_Handler,
		},
		{
			MethodName: "StartVirtualDesktop",
			Handler:    _ContainerService_StartVirtualDesktop_Handler,
		},
		{
			MethodName: "StopVirtualDesktop",
			Handler:    _ContainerService_StopVirtualDesktop_Handler,
		},
		{
			MethodName: "CreateChatModel",
			Handler:    _ContainerService_CreateChatModel_Handler,
		},
		{
			MethodName: "RemoveChatModel",
			Handler:    _ContainerService_RemoveChatModel_Handler,
		},
		{
			MethodName: "CreateAgent",
			Handler:    _ContainerService_CreateAgent_Handler,
		},
		{
			MethodName: "RemoveAgent",
			Handler:    _ContainerService_RemoveAgent_Handler,
		},
		{
			MethodName: "GetAgentSession",
			Handler:    _ContainerService_GetAgentSession_Handler,
		},
		{
			MethodName: "ClearAgentHistory",
			Handler:    _ContainerService_ClearAgentHistory_Handler,
		},
		{
			MethodName: "CompressAgentHistory",
			Handler:    _ContainerService_CompressAgentHistory_Handler,
		},
		{
			MethodName: "StopTask",
			Handler:    _ContainerService_StopTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BackupService",
			Handler:       _ContainerService_BackupService_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendMessage",
			Handler:       _ContainerService_SendMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "container.proto",
}
