// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: labor/v1/container.proto

package labor_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	ModelName     string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	AgentKind     string                 `protobuf:"bytes,7,opt,name=agent_kind,json=agentKind,proto3" json:"agent_kind,omitempty"`
	VncEnabled    bool                   `protobuf:"varint,8,opt,name=vnc_enabled,json=vncEnabled,proto3" json:"vnc_enabled,omitempty"`
	FtpEnabled    bool                   `protobuf:"varint,9,opt,name=ftp_enabled,json=ftpEnabled,proto3" json:"ftp_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServiceRequest) Reset() {
	*x = StartServiceRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceRequest) ProtoMessage() {}

func (x *StartServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceRequest.ProtoReflect.Descriptor instead.
func (*StartServiceRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{0}
}

func (x *StartServiceRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StartServiceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StartServiceRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StartServiceRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *StartServiceRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *StartServiceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StartServiceRequest) GetAgentKind() string {
	if x != nil {
		return x.AgentKind
	}
	return ""
}

func (x *StartServiceRequest) GetVncEnabled() bool {
	if x != nil {
		return x.VncEnabled
	}
	return false
}

func (x *StartServiceRequest) GetFtpEnabled() bool {
	if x != nil {
		return x.FtpEnabled
	}
	return false
}

type StartServiceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VisualDisplayPort int32                  `protobuf:"varint,1,opt,name=visual_display_port,json=visualDisplayPort,proto3" json:"visual_display_port,omitempty"`
	FtpPort           int32                  `protobuf:"varint,2,opt,name=ftp_port,json=ftpPort,proto3" json:"ftp_port,omitempty"`
	Success           bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartServiceResponse) Reset() {
	*x = StartServiceResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServiceResponse) ProtoMessage() {}

func (x *StartServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServiceResponse.ProtoReflect.Descriptor instead.
func (*StartServiceResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{1}
}

func (x *StartServiceResponse) GetVisualDisplayPort() int32 {
	if x != nil {
		return x.VisualDisplayPort
	}
	return 0
}

func (x *StartServiceResponse) GetFtpPort() int32 {
	if x != nil {
		return x.FtpPort
	}
	return 0
}

func (x *StartServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Service Messages
type StopServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceRequest) Reset() {
	*x = StopServiceRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceRequest) ProtoMessage() {}

func (x *StopServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceRequest.ProtoReflect.Descriptor instead.
func (*StopServiceRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{2}
}

func (x *StopServiceRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StopServiceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StopServiceRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopServiceResponse) Reset() {
	*x = StopServiceResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServiceResponse) ProtoMessage() {}

func (x *StopServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServiceResponse.ProtoReflect.Descriptor instead.
func (*StopServiceResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{3}
}

func (x *StopServiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type BackupServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupServiceRequest) Reset() {
	*x = BackupServiceRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupServiceRequest) ProtoMessage() {}

func (x *BackupServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupServiceRequest.ProtoReflect.Descriptor instead.
func (*BackupServiceRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{4}
}

func (x *BackupServiceRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *BackupServiceRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type BackupServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackupUrl     string                 `protobuf:"bytes,1,opt,name=backup_url,json=backupUrl,proto3" json:"backup_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupServiceResponse) Reset() {
	*x = BackupServiceResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupServiceResponse) ProtoMessage() {}

func (x *BackupServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupServiceResponse.ProtoReflect.Descriptor instead.
func (*BackupServiceResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{5}
}

func (x *BackupServiceResponse) GetBackupUrl() string {
	if x != nil {
		return x.BackupUrl
	}
	return ""
}

// Session Messages
type GetOrCreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateSessionRequest) Reset() {
	*x = GetOrCreateSessionRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateSessionRequest) ProtoMessage() {}

func (x *GetOrCreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateSessionRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrCreateSessionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *GetOrCreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *GetOrCreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Kind          string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_labor_v1_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{7}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *Message) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type GetOrCreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Messages      []*Message             `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateSessionResponse) Reset() {
	*x = GetOrCreateSessionResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateSessionResponse) ProtoMessage() {}

func (x *GetOrCreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateSessionResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrCreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetOrCreateSessionResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type CompressSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressSessionRequest) Reset() {
	*x = CompressSessionRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressSessionRequest) ProtoMessage() {}

func (x *CompressSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressSessionRequest.ProtoReflect.Descriptor instead.
func (*CompressSessionRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{9}
}

func (x *CompressSessionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CompressSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CompressSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CompressSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressSessionResponse) Reset() {
	*x = CompressSessionResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressSessionResponse) ProtoMessage() {}

func (x *CompressSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressSessionResponse.ProtoReflect.Descriptor instead.
func (*CompressSessionResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{10}
}

func (x *CompressSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CompressSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionRequest) Reset() {
	*x = RemoveSessionRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionRequest) ProtoMessage() {}

func (x *RemoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionRequest.ProtoReflect.Descriptor instead.
func (*RemoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveSessionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *RemoveSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RemoveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RemoveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSessionResponse) Reset() {
	*x = RemoveSessionResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSessionResponse) ProtoMessage() {}

func (x *RemoveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSessionResponse.ProtoReflect.Descriptor instead.
func (*RemoveSessionResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Dialogue Messages
type SendMessageToSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	IsStream      bool                   `protobuf:"varint,5,opt,name=is_stream,json=isStream,proto3" json:"is_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToSessionRequest) Reset() {
	*x = SendMessageToSessionRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToSessionRequest) ProtoMessage() {}

func (x *SendMessageToSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToSessionRequest.ProtoReflect.Descriptor instead.
func (*SendMessageToSessionRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{13}
}

func (x *SendMessageToSessionRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *SendMessageToSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SendMessageToSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageToSessionRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageToSessionRequest) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

type SendMessageToSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaContent  string                 `protobuf:"bytes,1,opt,name=delta_content,json=deltaContent,proto3" json:"delta_content,omitempty"` // 流式返回时的片段内容
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`               // 是否是最后一段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageToSessionResponse) Reset() {
	*x = SendMessageToSessionResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageToSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageToSessionResponse) ProtoMessage() {}

func (x *SendMessageToSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageToSessionResponse.ProtoReflect.Descriptor instead.
func (*SendMessageToSessionResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{14}
}

func (x *SendMessageToSessionResponse) GetDeltaContent() string {
	if x != nil {
		return x.DeltaContent
	}
	return ""
}

func (x *SendMessageToSessionResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// Task Messages
type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_labor_v1_container_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{15}
}

func (x *StopTaskRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StopTaskRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StopTaskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_labor_v1_container_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_labor_v1_container_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_labor_v1_container_proto_rawDescGZIP(), []int{16}
}

func (x *StopTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_labor_v1_container_proto protoreflect.FileDescriptor

const file_labor_v1_container_proto_rawDesc = "" +
	"\n" +
	"\x18labor/v1/container.proto\x12\blabor.v1\"\x93\x02\n" +
	"\x13StartServiceRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"agent_kind\x18\a \x01(\tR\tagentKind\x12\x1f\n" +
	"\vvnc_enabled\x18\b \x01(\bR\n" +
	"vncEnabled\x12\x1f\n" +
	"\vftp_enabled\x18\t \x01(\bR\n" +
	"ftpEnabled\"{\n" +
	"\x14StartServiceResponse\x12.\n" +
	"\x13visual_display_port\x18\x01 \x01(\x05R\x11visualDisplayPort\x12\x19\n" +
	"\bftp_port\x18\x02 \x01(\x05R\aftpPort\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"q\n" +
	"\x12StopServiceRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"/\n" +
	"\x13StopServiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"T\n" +
	"\x14BackupServiceRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\"6\n" +
	"\x15BackupServiceResponse\x12\x1d\n" +
	"\n" +
	"backup_url\x18\x01 \x01(\tR\tbackupUrl\"x\n" +
	"\x19GetOrCreateSessionRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"i\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\"j\n" +
	"\x1aGetOrCreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12-\n" +
	"\bmessages\x18\x02 \x03(\v2\x11.labor.v1.MessageR\bmessages\"u\n" +
	"\x16CompressSessionRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"R\n" +
	"\x17CompressSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"s\n" +
	"\x14RemoveSessionRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"1\n" +
	"\x15RemoveSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb1\x01\n" +
	"\x1bSendMessageToSessionRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1b\n" +
	"\tis_stream\x18\x05 \x01(\bR\bisStream\"^\n" +
	"\x1cSendMessageToSessionResponse\x12#\n" +
	"\rdelta_content\x18\x01 \x01(\tR\fdeltaContent\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\"n\n" +
	"\x0fStopTaskRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\",\n" +
	"\x10StopTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb6\x05\n" +
	"\x10ContainerService\x12M\n" +
	"\fStartService\x12\x1d.labor.v1.StartServiceRequest\x1a\x1e.labor.v1.StartServiceResponse\x12J\n" +
	"\vStopService\x12\x1c.labor.v1.StopServiceRequest\x1a\x1d.labor.v1.StopServiceResponse\x12P\n" +
	"\rBackupService\x12\x1e.labor.v1.BackupServiceRequest\x1a\x1f.labor.v1.BackupServiceResponse\x12_\n" +
	"\x12GetOrCreateSession\x12#.labor.v1.GetOrCreateSessionRequest\x1a$.labor.v1.GetOrCreateSessionResponse\x12P\n" +
	"\rRemoveSession\x12\x1e.labor.v1.RemoveSessionRequest\x1a\x1f.labor.v1.RemoveSessionResponse\x12V\n" +
	"\x0fCompressSession\x12 .labor.v1.CompressSessionRequest\x1a!.labor.v1.CompressSessionResponse\x12g\n" +
	"\x14SendMessageToSession\x12%.labor.v1.SendMessageToSessionRequest\x1a&.labor.v1.SendMessageToSessionResponse0\x01\x12A\n" +
	"\bStopTask\x12\x19.labor.v1.StopTaskRequest\x1a\x1a.labor.v1.StopTaskResponseB\n" +
	"Z\blabor.v1b\x06proto3"

var (
	file_labor_v1_container_proto_rawDescOnce sync.Once
	file_labor_v1_container_proto_rawDescData []byte
)

func file_labor_v1_container_proto_rawDescGZIP() []byte {
	file_labor_v1_container_proto_rawDescOnce.Do(func() {
		file_labor_v1_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_labor_v1_container_proto_rawDesc), len(file_labor_v1_container_proto_rawDesc)))
	})
	return file_labor_v1_container_proto_rawDescData
}

var file_labor_v1_container_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_labor_v1_container_proto_goTypes = []any{
	(*StartServiceRequest)(nil),          // 0: labor.v1.StartServiceRequest
	(*StartServiceResponse)(nil),         // 1: labor.v1.StartServiceResponse
	(*StopServiceRequest)(nil),           // 2: labor.v1.StopServiceRequest
	(*StopServiceResponse)(nil),          // 3: labor.v1.StopServiceResponse
	(*BackupServiceRequest)(nil),         // 4: labor.v1.BackupServiceRequest
	(*BackupServiceResponse)(nil),        // 5: labor.v1.BackupServiceResponse
	(*GetOrCreateSessionRequest)(nil),    // 6: labor.v1.GetOrCreateSessionRequest
	(*Message)(nil),                      // 7: labor.v1.Message
	(*GetOrCreateSessionResponse)(nil),   // 8: labor.v1.GetOrCreateSessionResponse
	(*CompressSessionRequest)(nil),       // 9: labor.v1.CompressSessionRequest
	(*CompressSessionResponse)(nil),      // 10: labor.v1.CompressSessionResponse
	(*RemoveSessionRequest)(nil),         // 11: labor.v1.RemoveSessionRequest
	(*RemoveSessionResponse)(nil),        // 12: labor.v1.RemoveSessionResponse
	(*SendMessageToSessionRequest)(nil),  // 13: labor.v1.SendMessageToSessionRequest
	(*SendMessageToSessionResponse)(nil), // 14: labor.v1.SendMessageToSessionResponse
	(*StopTaskRequest)(nil),              // 15: labor.v1.StopTaskRequest
	(*StopTaskResponse)(nil),             // 16: labor.v1.StopTaskResponse
}
var file_labor_v1_container_proto_depIdxs = []int32{
	7,  // 0: labor.v1.GetOrCreateSessionResponse.messages:type_name -> labor.v1.Message
	0,  // 1: labor.v1.ContainerService.StartService:input_type -> labor.v1.StartServiceRequest
	2,  // 2: labor.v1.ContainerService.StopService:input_type -> labor.v1.StopServiceRequest
	4,  // 3: labor.v1.ContainerService.BackupService:input_type -> labor.v1.BackupServiceRequest
	6,  // 4: labor.v1.ContainerService.GetOrCreateSession:input_type -> labor.v1.GetOrCreateSessionRequest
	11, // 5: labor.v1.ContainerService.RemoveSession:input_type -> labor.v1.RemoveSessionRequest
	9,  // 6: labor.v1.ContainerService.CompressSession:input_type -> labor.v1.CompressSessionRequest
	13, // 7: labor.v1.ContainerService.SendMessageToSession:input_type -> labor.v1.SendMessageToSessionRequest
	15, // 8: labor.v1.ContainerService.StopTask:input_type -> labor.v1.StopTaskRequest
	1,  // 9: labor.v1.ContainerService.StartService:output_type -> labor.v1.StartServiceResponse
	3,  // 10: labor.v1.ContainerService.StopService:output_type -> labor.v1.StopServiceResponse
	5,  // 11: labor.v1.ContainerService.BackupService:output_type -> labor.v1.BackupServiceResponse
	8,  // 12: labor.v1.ContainerService.GetOrCreateSession:output_type -> labor.v1.GetOrCreateSessionResponse
	12, // 13: labor.v1.ContainerService.RemoveSession:output_type -> labor.v1.RemoveSessionResponse
	10, // 14: labor.v1.ContainerService.CompressSession:output_type -> labor.v1.CompressSessionResponse
	14, // 15: labor.v1.ContainerService.SendMessageToSession:output_type -> labor.v1.SendMessageToSessionResponse
	16, // 16: labor.v1.ContainerService.StopTask:output_type -> labor.v1.StopTaskResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_labor_v1_container_proto_init() }
func file_labor_v1_container_proto_init() {
	if File_labor_v1_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_labor_v1_container_proto_rawDesc), len(file_labor_v1_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_labor_v1_container_proto_goTypes,
		DependencyIndexes: file_labor_v1_container_proto_depIdxs,
		MessageInfos:      file_labor_v1_container_proto_msgTypes,
	}.Build()
	File_labor_v1_container_proto = out.File
	file_labor_v1_container_proto_goTypes = nil
	file_labor_v1_container_proto_depIdxs = nil
}
